name: Deploy NuQ Postgres to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - apps/nuq-postgres/**
  workflow_dispatch:

jobs:
  push-app-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/nuq-postgres'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build NuQ Postgres Image'
        run: |
          docker build . --tag bonkboykz/nuq-postgres:latest
          docker push bonkboykz/nuq-postgres:latest
